name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 19
        uses: actions/setup-java@v2
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven
      - name: Validate, build and run tests
        run: mvn --batch-mode --update-snapshots verify

          - mvn javadoc:javadoc
          - git config --global user.email "grzegorzmal40@gmail.com"
          - git config --global user.name "Mational"
          - git remote add gh-pages https://${GITHUB_TOKEN}@github.com/owner/repo.git
          - git fetch gh-pages
          - git checkout gh-pages
          - git checkout master
          - mv target/apidocs apidocs
          - git add apidocs
          - git commit -m "Update javadocs"
          - git push gh-pages gh-pages
  
      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          # email subject
          subject: ${{ github.job }} job of ${{ github.repository }} has ${{ job.status }}
          # email body as text
          body: ${{ github.job }} job in worflow ${{ github.workflow }} of ${{ github.repository }} has ${{ job.status }}
          # comma-separated string, send email to
          to: pro.computer1000@gmail.com,grzegorzmal40@gmail.com,katrecat33@gmail.com
          # from email name
          from: Github Action
